"""Add steps column to Workflow

Revision ID: 69b3f9544a99
Revises: 4425c193df8a
Create Date: 2025-01-27 22:03:05.184107

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '69b3f9544a99'
down_revision = '4425c193df8a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workflow', schema=None) as batch_op:
        batch_op.add_column(sa.Column('steps', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('execution_logs', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workflow', schema=None) as batch_op:
        batch_op.drop_column('execution_logs')
        batch_op.drop_column('steps')

    # ### end Alembic commands ###
